version: '3' 
services:


  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    networks:
      - core
#    volumes:
#      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-swarm.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 50070:50070

  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    networks:
      - core
#    volumes:
#      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-swarm.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  examples:
    image: hdfs_examples:latest
    networks:
      - core
      
        
        
#volumes:
#  datanode:
#  namenode:

networks:
  core:
#    external: true